SELECT
CO.CORP_SEQ
, Y.YEAR
, KPI.*
FROM CORP_INFO CO
INNER JOIN Y
INNER JOIN
(
	  SELECT
     L1.KPI_CD AS L1_KPI_CD
     , L1.KPI_NM AS L1_KPI_NM
     , L2.KPI_CD AS L2_KPI_CD
     , L2.KPI_NM AS L2_KPI_NM
     , L3.KPI_CD AS L3_KPI_CD
     , L3.KPI_NM AS L3_KPI_NM
     FROM
     (
       SELECT * FROM KPI WHERE LEVEL = 1
     ) L1
     INNER JOIN
     (
       SELECT * FROM KPI WHERE LEVEL = 2
     ) L2 ON (L1.KPI_CD = L2.P_KPI_CD)
     INNER JOIN
     (
       SELECT * FROM KPI WHERE LEVEL = 3
     ) L3 ON (L2.KPI_CD = L3.P_KPI_CD)
) KPI
WHERE Y.YEAR = 2017
ORDER BY CO.CORP_SEQ, Y.YEAR, KPI.L3_KPI_CD